name: "Workflow Exemplo"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer o checkout do código 
        # essa é a action que permite ter acesso ao código durante a execução do job.
        uses: actions/checkout@v4
        with:
          ref: deploy # ref é o input que diz qual será o nome da branch que utilizaremos.
      - name: "instalar Node.JS"
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar as dependencias
        run: npm ci
      - name: Instalar angular CLI
        run: npm install --global @angular/cli
      - name: Build - Gerar o font de produção
        run: ng build --configuration production --base-href=/proway-superDev-escola-ng/
  construir:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: "Instalar as dependencias"
        run: echo 'Instalando as dependencias'

        